# -*- coding: utf-8 -*-
"""To-do app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHime1ijFfI3onH7lESzZKqAfE5a0ZJ7
"""

# creating a to do list

tasks=[]
def display_menu():
  print("\nTo-do list men :")
  print( "1. add task")
  print( "2. view task")
  print( "3. quit")

def add_task():
  task=input("Enter a task :")
  tasks.append(task)
  print(f"Task '{task}' added to the list")

def view_task():
  if tasks:
    print("\nYour To-do list :")
    for index,task in enumerate(tasks,start=1):
      print(f"{index}.{task}")

    else : print("Your to-do list is empty!")

  while  True:
    choice=input("choose an option : ")

    if choice=="1":
      display_menu()
    elif choice=="2":
      view_task()
    elif choice=="3":
      print("exiting the app , take care !")
      break
    else : print("invalide choice please try again ")